### ISSUE TITLE
'Namespace' object has no attribute 'resume_prefix_pose'

### ISSUE THREAD

**Issue by ksarker1** [zhiqiangdon/pose-adv-aug#2]
Hello!

Thanks for sharing this great work! I would like to implement it in my research. But, I had faced an error after installing prerequisites. 
`Traceback (most recent call last):
  File "stack-hg.py", line 269, in <module>
    main()
  File "stack-hg.py", line 30, in main
    opt = TrainOptions().parse()
File "$HOME/pose-adv-aug/options/base_options.py", line 62, in parse
    if self.opt.resume_prefix_pose != '':
AttributeError: 'Namespace' object has no attribute 'resume_prefix_pose'
 `
I think the error is internal, I guess. Can you shred some light on this issue? Thanks in advance..

**Comment by zkyf** [comment]
got the same problem. has anyone solved this?

**Comment by ksarker1** [comment]
I had to comment out the lines on options/base_options.py file. Hope this helps!

**Comment by zouxuelian** [comment]
1、改动 
  if opt.resume_prefix_pose != '':
    # if opt.load_prefix_pose != '':
        # if 'pth' in opt.resume_prefix:
        #     trunc_index = opt.resume_prefix.index('pth')
        #     opt.resume_prefix = opt.resume_prefix[0:trunc_index - 1]
        # checkpoint.save_prefix = os.path.join(exp_dir, opt.load_prefix_pose)
        # checkpoint.load_prefix = os.path.join(exp_dir, opt.load_prefix_pose)[0:-1]
        checkpoint.save_prefix = os.path.join(exp_dir, opt.resume_prefix_pose)
        checkpoint.load_prefix = os.path.join(exp_dir, opt.resume_prefix_pose)[0:-1]
        checkpoint.load_checkpoint(net, optimizer, train_history)

2、改动
self.parser.add_argument('--load_checkpoint', type=bool, default=False,
                                 help='resume from checkpoint model')
        self.parser.add_argument('--load_checkpoint_pose', type=bool, default=False,
                                 help='use checkpoint model')
        self.parser.add_argument('--load_checkpoint_asn', type=bool, default=False,
                                 help='use checkpoint model')
        self.parser.add_argument('--resume_prefix_pose', type=str, default='',
                                 help='checkpoint name for resuming')
